---
apiVersion: v1
kind: Service
metadata:
  name: chango-admin-oci-service
  namespace: {{ .Values.namespace }}
  labels:
    app: chango-admin-oci
    component: chango
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.server.port }}
      targetPort: rest
      protocol: TCP
      name: rest
  selector:
    app: chango-admin-oci
